import type { AmenityKey, EquipmentKey, GymSegment, VibeTag } from "@/lib/types/scout";

/** Phrase → key dictionaries for the deterministic fallback parser.
 *  Longest phrase wins; all matching is lowercase substring/phrase based. */

export const AMENITY_SYNONYMS: Record<AmenityKey, string[]> = {
  sauna: ["sauna", "saunas"],
  cold_plunge: ["cold plunge", "cold tub", "ice bath", "plunge pool", "cold-plunge"],
  steam_room: ["steam room", "steamroom"],
  pool: ["pool", "swimming", "lap pool", "swim"],
  recovery_room: ["recovery room", "recovery area", "recovery suite"],
  open_24h: ["24 hour", "24-hour", "24/7", "24 7", "twenty four hour", "open all night", "always open"],
  classes: ["classes", "group classes", "group fitness", "class schedule"],
  personal_training: ["personal training", "personal trainer", "pt sessions", "coaching"],
  turf_area: ["turf", "turf area", "sled track"],
  cardio_zone: ["cardio", "cardio zone"],
  basketball_court: ["basketball", "hoops", "basketball court"],
  day_pass: ["day pass", "drop in", "drop-in", "daypass", "guest pass"],
  parking: ["parking", "parking lot", "free parking"],
  lockers: ["lockers", "locker room", "locker rooms"],
  showers: ["showers", "shower"],
  towel_service: ["towel service", "towels"],
  wifi: ["wifi", "wi-fi", "wireless"],
  juice_bar: ["juice bar", "smoothie bar", "smoothies", "protein shakes"],
  cafe: ["cafe", "coffee", "coffee shop"],
  coworking_space: ["coworking", "co-working", "work between sets", "laptop", "remote work"],
  womens_area: ["women's area", "womens area", "women's only area", "women's section", "ladies area", "ladies-only area"],
  womens_only: ["women's only gym", "womens only gym", "women only", "ladies only", "ladies-only gym", "female only"],
  childcare: ["childcare", "child care", "kids club", "daycare", "babysitting"],
  tanning: ["tanning", "tanning beds", "uv tanning", "tanning booth"],
  hydromassage: ["hydromassage", "hydro massage", "water massage", "massage beds"],
  spin_studio: ["spin studio", "cycling studio", "indoor cycling studio", "rhythm cycling"],
  retail_shop: ["retail", "pro shop", "retail shop", "merch", "boutique shop"],
  props_provided: ["props provided", "mats provided", "props included", "equipment provided"],
  open_gym: ["open gym", "open gym access", "open floor"],
  chalk_allowed: ["chalk allowed", "chalk friendly", "chalk"],
  wheelchair_accessible: ["wheelchair accessible", "wheelchair", "ada accessible", "accessible gym"],
  accessible_restrooms: ["accessible restrooms", "accessible bathroom", "ada restroom"],
};

export const EQUIPMENT_SYNONYMS: Record<EquipmentKey, string[]> = {
  squat_rack: ["squat rack", "squat racks", "racks", "rack"],
  power_rack: ["power rack", "power cage", "cage"],
  platform: ["platform", "platforms", "lifting platform", "deadlift platform", "olympic platform", "oly platform"],
  dumbbells: ["dumbbell", "dumbbells", "db's", "dbs"],
  barbells: ["barbell", "barbells", "bars"],
  kettlebells: ["kettlebell", "kettlebells", "kb"],
  ghd: ["ghd", "glute ham", "glute-ham", "glute ham developer"],
  sled: ["sled", "prowler", "push sled"],
  ski_erg: ["ski erg", "skierg", "ski-erg"],
  assault_bike: ["assault bike", "air bike", "airbike", "echo bike", "fan bike"],
  rower: ["rower", "rowing machine", "rowers", "erg", "concept 2", "concept2"],
  reverse_hyper: ["reverse hyper", "reverse-hyper", "reverse hyperextension"],
  belt_squat: ["belt squat", "belt-squat"],
  comp_bench: ["competition bench", "comp bench"],
  cable_machine: ["cable machine", "cables", "cable crossover", "functional trainer"],
  leg_press: ["leg press"],
  smith_machine: ["smith machine", "smith"],
  hack_squat: ["hack squat"],
  pull_up_bar: ["pull up bar", "pull-up bar", "pullup bar", "rig"],
  dip_station: ["dip station", "dip bars", "dips"],
  monolift: ["monolift", "mono lift"],
  climbing_wall: ["climbing wall", "bouldering", "rock wall", "rock climbing"],
  hip_thrust: ["hip thrust"],
  leg_extension: ["leg extension"],
  leg_curl: ["leg curl", "hamstring curl"],
  abductor_adductor: ["abductor", "adductor"],
  calf_machine: ["calf raise machine", "calf machine"],
  stepmill: ["stepmill", "stairmaster", "stair master", "stairmill"],
  specialty_bars: ["specialty bars", "safety squat bar", "ssb", "trap bar", "hex bar", "buffalo bar", "cambered bar", "axle bar"],
  nordic_bench: ["nordic bench", "nordic curl"],
  treadmill: ["treadmill", "treadmills"],
  elliptical: ["elliptical", "ellipticals", "cross trainer"],
  upright_bike: ["upright bike", "exercise bike", "stationary bike"],
  recumbent_bike: ["recumbent bike", "recumbent"],
  stair_climber: ["stair climber", "stair stepper"],
  reformer: ["reformer", "reformers", "pilates reformer"],
  pilates_tower: ["pilates tower", "reformer tower"],
  cadillac: ["cadillac", "trapeze table"],
  pilates_chair: ["pilates chair", "wunda chair"],
  pilates_barrel: ["pilates barrel", "spine corrector", "ladder barrel"],
  aerial_rig: ["aerial rig", "aerial silks", "aerial hammock", "aerial yoga"],
  heavy_bag: ["heavy bag", "heavy bags", "punching bag", "punching bags", "boxing bag"],
  boxing_ring: ["boxing ring"],
  mma_cage: ["mma cage", "octagon", "fighting cage"],
  mats: ["mats", "mat space", "matted area", "wrestling mats", "grappling mats"],
  spin_bike: ["spin bike", "spin bikes", "indoor cycling", "cycling bikes"],
  curved_treadmill: ["curved treadmill", "assault runner", "manual treadmill", "trueform"],
  versaclimber: ["versaclimber", "vertical climber", "maxiclimber", "climbing machine"],
  jacobs_ladder: ["jacobs ladder", "jacob's ladder", "ladder climber"],
  arc_trainer: ["arc trainer", "cybex arc", "arc cross trainer"],
  incline_trainer: ["incline trainer", "incline treadmill", "x22i"],
  water_rower: ["water rower", "waterrower", "water resistance rower"],
  recumbent_stepper: ["recumbent stepper", "nustep", "seated stepper"],
  upper_body_ergometer: ["upper body ergometer", "ube", "arm bike", "arm ergometer"],
  chest_press_machine: ["chest press machine", "seated chest press", "pin loaded chest press"],
  shoulder_press_machine: ["shoulder press machine", "seated shoulder press", "overhead press machine"],
  lat_pulldown_machine: ["lat pulldown machine", "lat pull down", "pulldown machine"],
  seated_row_machine: ["seated row machine", "seated cable row", "low row machine"],
  pec_deck: ["pec deck", "chest fly machine", "pec fly machine", "butterfly machine"],
  rear_delt_machine: ["rear delt machine", "reverse pec deck", "reverse fly machine"],
  lateral_raise_machine: ["lateral raise machine", "lat raise machine", "deltoid machine"],
  preacher_curl_machine: ["preacher curl machine", "bicep curl machine", "seated curl machine", "arm curl machine"],
  tricep_extension_machine: ["tricep press machine", "tricep extension machine", "triceps machine"],
  tricep_pushdown_machine: ["tricep pushdown machine", "seated tricep pushdown", "triceps pushdown"],
  assisted_pull_up_dip_machine: ["assisted pull up machine", "assisted dip machine", "gravitron", "assisted chin up"],
  ab_crunch_machine: ["ab crunch machine", "abdominal machine", "ab machine", "seated crunch machine"],
  back_extension_machine: ["back extension machine", "lower back machine", "lumbar extension machine"],
  torso_rotation_machine: ["torso rotation machine", "oblique machine", "rotary torso machine", "ab twist machine"],
  glute_machine: ["glute machine", "glute kickback machine", "hip extension machine"],
  lat_pullover_machine: ["lat pullover machine", "pullover machine", "nautilus pullover"],
  cable_crossover: ["cable crossover", "functional trainer", "dual cable machine"],
  iso_lateral_chest_press: ["iso lateral chest press", "hammer strength chest press", "plate loaded chest press"],
  iso_lateral_incline_press: ["plate loaded incline press", "hammer strength incline", "iso incline chest press"],
  iso_lateral_shoulder_press: ["plate loaded shoulder press", "hammer strength shoulder press", "iso overhead press"],
  iso_lateral_row: ["iso lateral row", "hammer strength row", "plate loaded row"],
  iso_lateral_pulldown: ["plate loaded lat pulldown", "hammer strength pulldown", "iso lat pulldown"],
  t_bar_row_machine: ["t-bar row machine", "landmine row", "chest supported t-bar row"],
  pendulum_squat: ["pendulum squat machine", "arc squat", "arch squat machine"],
  v_squat: ["v squat machine", "angled squat machine", "plate loaded v-squat"],
  linear_leg_press: ["45 degree leg press", "angled leg press", "incline leg press"],
  seated_dip_machine: ["plate loaded dip machine", "machine dip", "chest dip machine"],
  landmine_station: ["landmine attachment", "landmine press station", "viking press"],
  adjustable_bench: ["adjustable bench", "fid bench", "multi bench"],
  flat_bench: ["flat bench", "press bench", "weight bench"],
  incline_bench: ["incline bench", "incline press bench", "upper chest bench"],
  decline_bench: ["decline bench", "decline press bench", "lower chest bench"],
  preacher_bench: ["preacher bench", "preacher curl bench", "scott bench"],
  adjustable_dumbbells: ["adjustable dumbbells", "loadable dumbbells", "selectorized dumbbells", "powerblock"],
  bumper_plates: ["bumper plates", "rubber plates", "olympic bumpers"],
  weight_plates: ["weight plates", "iron plates", "olympic plates"],
  change_plates: ["change plates", "fractional plates", "micro plates"],
  trap_bar: ["trap bar", "hex bar", "deadlift bar"],
  ez_curl_bar: ["ez curl bar", "ez bar", "curl bar"],
  safety_squat_bar: ["safety squat bar", "ssb", "safety bar"],
  swiss_bar: ["swiss bar", "football bar", "multi grip bar"],
  fat_grip_bar: ["fat bar", "axle bar", "thick grip bar"],
  half_rack: ["half rack", "open rack", "half power rack"],
  wall_mounted_rack: ["wall mounted rack", "fold back rack", "wall rack"],
  deadlift_jack: ["deadlift jack", "plate jack", "deadlift bar jack"],
  resistance_bands: ["resistance bands", "power bands", "loop bands", "mobility bands"],
  jerk_blocks: ["jerk blocks", "pulling blocks", "weightlifting blocks"],
  battle_ropes: ["battle rope", "battling ropes", "conditioning ropes", "heavy rope"],
  plyo_boxes: ["plyometric box", "jump box", "plyo box", "box jumps"],
  medicine_balls: ["med ball", "medicine ball", "weighted ball"],
  slam_balls: ["slam ball", "dead ball", "no bounce ball"],
  wall_balls: ["wall ball", "soft med ball", "wall ball target"],
  suspension_trainer: ["trx", "suspension trainer", "suspension straps", "bodyweight trainer"],
  gymnastic_rings: ["gymnastic rings", "olympic rings", "still rings", "muscle up rings"],
  parallettes: ["parallettes", "parallette bars", "p bars", "mini parallel bars"],
  climbing_rope: ["climbing rope", "rope climb", "gym rope"],
  jump_ropes: ["jump rope", "speed rope", "skipping rope", "double under rope"],
  agility_ladder: ["agility ladder", "speed ladder", "footwork ladder"],
  ab_wheel: ["ab wheel", "ab roller", "core wheel"],
  weighted_vest: ["weighted vest", "weight vest", "ruck vest"],
  sandbags: ["sandbag", "training sandbag", "weighted sandbag"],
  tires: ["tire flip", "flip tire", "training tire", "tractor tire"],
  atlas_stones: ["atlas stone", "strongman stone", "lifting stone"],
  yoke: ["strongman yoke", "yoke carry", "yoke walk"],
  farmers_handles: ["farmers handles", "farmers walk handles", "trap handles"],
  log_bar: ["log bar", "strongman log", "log press"],
  balance_trainer: ["bosu", "bosu ball", "balance trainer", "half ball"],
  stability_ball: ["stability ball", "swiss ball", "exercise ball", "physio ball"],
  vibration_plate: ["vibration plate", "power plate", "whole body vibration"],
  ballet_barre: ["ballet barre", "wall barre", "freestanding barre"],
  spring_wall: ["spring wall", "wall unit", "springboard", "pilates wall springs"],
  magic_circle: ["magic circle", "pilates ring", "fitness circle"],
  spine_corrector: ["spine corrector", "small barrel corrector", "pilates corrector"],
  jump_board: ["jump board", "reformer jumpboard", "cardio jumpboard"],
  yoga_blocks: ["yoga blocks", "yoga brick", "foam block", "cork block"],
  yoga_straps: ["yoga strap", "stretching strap", "yoga belt"],
  yoga_bolsters: ["yoga bolster", "restorative bolster", "support pillow"],
  yoga_wheel: ["yoga wheel", "back wheel", "dharma wheel"],
  yoga_swing: ["yoga swing", "yoga trapeze", "aerial yoga hammock"],
  pilates_mat: ["pilates mat", "exercise mat", "thick mat"],
  toning_balls: ["toning balls", "barre ball", "mini pilates ball", "soft weight balls"],
  balance_pad: ["balance pad", "stability pad", "wobble cushion"],
  balance_board: ["balance board", "wobble board", "rocker board"],
  ankle_weights: ["ankle weights", "wrist weights", "barre weights", "wearable weights"],
  foam_roller: ["foam roller", "mobility roller", "myofascial roller", "trigger point roller"],
  speed_bag: ["speed bag", "speedball", "boxing speed bag"],
  double_end_bag: ["double end bag", "floor to ceiling bag"],
  muay_thai_bag: ["muay thai bag", "banana bag", "long heavy bag"],
  uppercut_bag: ["uppercut bag", "angle bag", "upper cut bag"],
  free_standing_bag: ["free standing bag", "standalone heavy bag", "base bag"],
  body_opponent_bag: ["body opponent bag", "bob dummy", "free standing dummy"],
  reflex_bag: ["reflex bag", "cobra bag", "free standing reflex bag", "speed reflex bag"],
  aqua_bag: ["aqua bag", "water heavy bag", "water filled bag"],
  grappling_dummy: ["grappling dummy", "bjj dummy", "throwing dummy", "submission dummy"],
  wing_chun_dummy: ["wing chun dummy", "wooden dummy", "mook jong"],
  focus_mitts_area: ["focus mitts", "punch mitts", "thai pads", "kick shield"],
  normatec_boots: ["normatec", "compression boots", "recovery boots", "pneumatic compression"],
  massage_gun: ["massage gun", "theragun", "percussion massager", "hypervolt"],
  stretching_station: ["stretch cage", "stretching table", "assisted stretching", "mobility station"],
  inversion_table: ["inversion table", "inversion therapy", "decompression table"],
};

export const SEGMENT_SYNONYMS: Record<GymSegment, string[]> = {
  strength: ["powerlifting", "powerlifter", "strength gym", "strength training", "weightlifting", "olympic lifting", "oly lifting", "bodybuilding", "iron gym", "barbell club", "lifting gym", "serious gym", "hardcore gym", "heavy lifting", "lift heavy", "heavy weights", "heavy training"],
  crossfit: ["crossfit", "cross fit", "wod", "functional fitness", "box"],
  big_box: ["big box", "chain gym", "commercial gym", "regular gym"],
  boutique: ["boutique", "studio", "f45", "orangetheory", "otf", "9round", "barry's"],
  climbing: ["climbing", "bouldering", "rock climbing", "climbing gym"],
  yoga_pilates: ["yoga", "pilates", "hot yoga", "vinyasa", "reformer"],
  mma: ["mma", "boxing", "muay thai", "jiu jitsu", "bjj", "kickboxing", "martial arts"],
  recovery: ["recovery", "wellness", "spa", "contrast therapy", "sauna studio"],
  luxury: ["luxury", "high end", "high-end", "upscale", "bougie", "fancy", "premium club", "country club", "resort", "athletic club"],
  cycling: ["cycling", "spin", "spin studio", "indoor cycling", "soulcycle", "cyclebar", "cycle bar", "rhythm ride"],
  barre: ["barre", "barre studio", "pure barre", "barre class"],
};

/** Vibe descriptors → SOFT vibe tags (boost, never exclude — Kodawari rule). */
export const VIBE_SYNONYMS: Record<string, VibeTag[]> = {
  trendy: ["trendy", "aesthetic"],
  instagram: ["trendy", "aesthetic", "social"],
  instagrammable: ["trendy", "aesthetic"],
  influencer: ["trendy", "aesthetic", "social"],
  vibey: ["serene", "aesthetic"],
  "good vibes": ["serene", "aesthetic"],
  aesthetic: ["aesthetic"],
  beautiful: ["aesthetic"],
  social: ["social"],
  chill: ["serene"],
  calm: ["serene"],
  peaceful: ["serene"],
  zen: ["serene"],
  "old school": ["old_school"],
  "old-school": ["old_school"],
  "no frills": ["no_frills"],
  "no-frills": ["no_frills"],
  gritty: ["no_frills", "hardcore"],
  hardcore: ["hardcore"],
  intense: ["hardcore"],
  community: ["community"],
  welcoming: ["community", "beginner_friendly"],
  "beginner friendly": ["beginner_friendly"],
  "judgement free": ["beginner_friendly"],
  "judgment free": ["beginner_friendly"],
};

/** Known equipment brands (matched case-insensitively as whole words/phrases). */
export const KNOWN_BRANDS = [
  "rogue",
  "eleiko",
  "hammer strength",
  "life fitness",
  "technogym",
  "precor",
  "cybex",
  "concept2",
  "concept 2",
  "assault",
  "york",
  "kabuki",
  "titan",
  "matrix",
  "nautilus",
  "arsenal strength",
  "prime",
  "watson",
];

/** Tampa neighborhoods — canonical names must match seed data exactly. */
export const NEIGHBORHOOD_SYNONYMS: Record<string, string[]> = {
  "Downtown": ["downtown"],
  "Channel District": ["channel district", "channelside", "water street"],
  "Hyde Park": ["hyde park", "soho", "howard ave"],
  "South Tampa": ["south tampa", "bayshore", "palma ceia", "ballast point"],
  "Seminole Heights": ["seminole heights"],
  "Ybor City": ["ybor", "ybor city"],
  "Westshore": ["westshore", "west shore", "international plaza"],
  "Carrollwood": ["carrollwood"],
  "North Tampa": ["north tampa", "usf", "university area", "temple terrace"],
};
